DROP TABLE IF EXISTS findings;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS run_steps;
DROP TABLE IF EXISTS runs;
DROP TABLE IF EXISTS out_of_scopes;
DROP TABLE IF EXISTS targets;
DROP TABLE IF EXISTS programs;
DROP TABLE IF EXISTS users;
